//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Please update missing fields before continue!.
        /// </summary>
        internal static string default_validation_error {
            get {
                return ResourceManager.GetString("default_validation_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not a valid email address..
        /// </summary>
        internal static string fluentvalidation_email_error {
            get {
                return ResourceManager.GetString("fluentvalidation_email_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should be equal to {PropertyValue}..
        /// </summary>
        internal static string fluentvalidation_equal_error {
            get {
                return ResourceManager.GetString("fluentvalidation_equal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be {MaxLength} characters in length. You entered{TotalLength} characters..
        /// </summary>
        internal static string fluentvalidation_exact_length_error {
            get {
                return ResourceManager.GetString("fluentvalidation_exact_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {From} and {To}. You entered {Value}..
        /// </summary>
        internal static string fluentvalidation_exclusivebetween_error {
            get {
                return ResourceManager.GetString("fluentvalidation_exclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is existed..
        /// </summary>
        internal static string fluentvalidation_existed {
            get {
                return ResourceManager.GetString("fluentvalidation_existed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName}  must be greater than {ComparisonValue}..
        /// </summary>
        internal static string fluentvalidation_greaterthan_error {
            get {
                return ResourceManager.GetString("fluentvalidation_greaterthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be greater than or equal to {ComparisonValue}..
        /// </summary>
        internal static string fluentvalidation_greaterthanorequal_error {
            get {
                return ResourceManager.GetString("fluentvalidation_greaterthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {From} and {To}. You entered {Value}..
        /// </summary>
        internal static string fluentvalidation_inclusivebetween_error {
            get {
                return ResourceManager.GetString("fluentvalidation_inclusivebetween_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be between {MinLength} and {MaxLength} characters. You entered {TotalLength} characters..
        /// </summary>
        internal static string fluentvalidation_length_error {
            get {
                return ResourceManager.GetString("fluentvalidation_length_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than {ComparisonValue}..
        /// </summary>
        internal static string fluentvalidation_lessthan_error {
            get {
                return ResourceManager.GetString("fluentvalidation_lessthan_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must be less than or equal to {ComparisonValue}..
        /// </summary>
        internal static string fluentvalidation_lessthanorequal_error {
            get {
                return ResourceManager.GetString("fluentvalidation_lessthanorequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not a valid number..
        /// </summary>
        internal static string fluentvalidation_mustbenumberic {
            get {
                return ResourceManager.GetString("fluentvalidation_mustbenumberic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not a valid phone number..
        /// </summary>
        internal static string fluentvalidation_mustphonefax {
            get {
                return ResourceManager.GetString("fluentvalidation_mustphonefax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not contain numberic..
        /// </summary>
        internal static string fluentvalidation_notcontainnumberic {
            get {
                return ResourceManager.GetString("fluentvalidation_notcontainnumberic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not contain spaces..
        /// </summary>
        internal static string fluentvalidation_notcontainspace {
            get {
                return ResourceManager.GetString("fluentvalidation_notcontainspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not contain spaces and special characters..
        /// </summary>
        internal static string fluentvalidation_notcontainspaceandspecialcharacters {
            get {
                return ResourceManager.GetString("fluentvalidation_notcontainspaceandspecialcharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} must not contain special characters..
        /// </summary>
        internal static string fluentvalidation_notcontainspecialcharacters {
            get {
                return ResourceManager.GetString("fluentvalidation_notcontainspecialcharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not be empty..
        /// </summary>
        internal static string fluentvalidation_notempty_error {
            get {
                return ResourceManager.GetString("fluentvalidation_notempty_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} should not be equal to {PropertyValue}..
        /// </summary>
        internal static string fluentvalidation_notequal_error {
            get {
                return ResourceManager.GetString("fluentvalidation_notequal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not existed..
        /// </summary>
        internal static string fluentvalidation_notexisted {
            get {
                return ResourceManager.GetString("fluentvalidation_notexisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName}must not be empty..
        /// </summary>
        internal static string fluentvalidation_notnull_error {
            get {
                return ResourceManager.GetString("fluentvalidation_notnull_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is incorect..
        /// </summary>
        internal static string fluentvalidation_password_incorect {
            get {
                return ResourceManager.GetString("fluentvalidation_password_incorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified condition was not met for {PropertyName}...
        /// </summary>
        internal static string fluentvalidation_predicate_error {
            get {
                return ResourceManager.GetString("fluentvalidation_predicate_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} is not in the correct format..
        /// </summary>
        internal static string fluentvalidation_regex_error {
            get {
                return ResourceManager.GetString("fluentvalidation_regex_error", resourceCulture);
            }
        }
    }
}
